data:
  embeddings_path: data/processed/embeddings.json
  fine_tuning_data: data/fine_tuning_data.jsonl
  pdf_path: data/raw/48_laws_of_power.pdf
  text_path: data/processed/48_laws_of_power.txt
model:
  embedding_model: paraphrase-multilingual-mpnet-base-v2
  llm_model: microsoft/Phi-3-mini-4k-instruct
  llm_params:
    max_length: 200
    temperature: 0.7
    torch_dtype: float16
